import type { Metadata } from "next";
import { Breadcrumbs, PageShell } from "../../components/SiteChrome";
import { laws } from "../../data/laws";
import { lawPath } from "../../data/navigation";

export const metadata: Metadata = { title: "Indigenous Laws & Constitutional Texts | OpenCourt", description: "Verified federal laws and constitutional provisions central to Indigenous peoples, rights, jurisdiction and legal relationships in Canada." };

export default function LawsPage() {
  return <PageShell><section className="page-hero laws-hero"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Laws" }]} /><div className="page-hero-grid"><div><p className="kicker">{laws.length} primary-source verified instruments</p><h1>Laws &amp; constitutional texts</h1></div><p>Open any law for a detailed guide to what it does, who it affects, its key provisions, history, related cases, legal significance, and official sources.</p></div></section><section className="laws-section"><div className="laws-heading"><div><p className="section-number">Impact collection</p><h2>Constitutional, federal &amp; provincial laws</h2></div><p>This collection prioritizes instruments with broad constitutional, treaty, governance, land, fiscal, family, language, and jurisdictional effects. Every published record links to the official current text.</p></div><div className="law-grid">{laws.map((law, index) => <article key={law.id}><div className="law-card-top"><span>{String(index + 1).padStart(2, "0")}</span><em>{law.lawType}</em></div><h3>{law.title}</h3><b>{law.citation}</b><p>{law.plainLanguageSummary}</p><dl><div><dt>Jurisdiction</dt><dd>{law.jurisdiction}</dd></div><div><dt>Status</dt><dd>{law.currentStatus}</dd></div><div><dt>Impact</dt><dd>{law.impactScore}/100</dd></div><div><dt>Verification</dt><dd>{law.verified.replaceAll("_", " ")}</dd></div></dl><div className="law-topics">{law.categories.slice(0, 5).map((category) => <span key={category}>{category}</span>)}</div><a className="law-card-action" href={lawPath(law.slug)}>View Law Page <span aria-hidden="true">→</span></a></article>)}</div><div className="legal-notice"><strong>Consult the current consolidation.</strong><p>Amendments and coming-into-force rules can change the law. Always check the official source linked on the record before relying on a provision.</p></div></section></PageShell>;
}
