"use client";

import { useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { courtLevels, decade, emptyFilters, filterCases, groups, jurisdictions, normalize, percent, rowsFor } from '../lib/coverage/model';
import type { CoverageCase, CoverageRow, CoverageSnapshot, Filters, QualityKey } from '../lib/coverage/model';

const qualityKeys: QualityKey[] = ['Verified','Secondary Source','Needs Verification','Draft','Published','Missing primary source','Missing community','Missing legal topics','Treaty association to review','Missing related cases','Placeholder text','Verification older than 365 days','Missing verification date'];
const unique = (values: string[]) => [...new Set(values)].sort((a,b) => a.localeCompare(b));
const date = (value: string) => value ? value.slice(0,10) : '—';
const displayNumber = (value: number | null) => value === null ? '—' : value.toLocaleString();
type Inspect = (title: string, records: CoverageCase[]) => void;

function Section({ id, title, note, children }: { id: string; title: string; note?: string; children: ReactNode }) {
  return <section id={id} className="coverage-panel" aria-labelledby={`${id}-heading`}><h2 id={`${id}-heading`}>{title}</h2>{note && <p className="coverage-note">{note}</p>}{children}</section>;
}
function Priority({ value }: { value: CoverageRow['priority'] }) { return <span className={`coverage-priority priority-${value.split(' ')[0].toLowerCase()}`}>{value}</span>; }
function CoverageTable({ rows, inspect, dates = false, extra }: { rows: CoverageRow[]; inspect: Inspect; dates?: boolean; extra?: { headings: string[]; cells: (row: CoverageRow) => ReactNode[] } }) {
  return <div className="coverage-table-wrap" tabIndex={0} role="region" aria-label="Coverage table"><table className="coverage-table"><thead><tr><th scope="col">Category</th><th scope="col">Cases</th><th scope="col">% of selection</th>{dates ? <><th scope="col">Earliest decision</th><th scope="col">Latest decision</th></> : <><th scope="col">Verified</th><th scope="col">Ongoing</th></>}{extra?.headings.map((heading) => <th scope="col" key={heading}>{heading}</th>)}<th scope="col">Priority</th></tr></thead><tbody>{rows.map((row) => <tr key={row.name}><th scope="row"><button className="coverage-link" onClick={() => inspect(row.name,row.records)}>{row.name}</button><span className="coverage-bar" aria-hidden="true"><i style={{ width:row.share === '—' ? '0%' : row.share }} /></span></th><td>{row.count}</td><td>{row.share}</td>{dates ? <><td>{date(row.first)}</td><td>{date(row.latest)}</td></> : <><td>{row.verified}</td><td>{row.ongoing}</td></>}{extra?.cells(row).map((cell,index) => <td key={index}>{cell}</td>)}<td><Priority value={row.priority} /></td></tr>)}</tbody></table>{!rows.length && <p className="coverage-empty">No categories match this view.</p>}</div>;
}
function Metric({ label, count, onClick, note }: { label: string; count: number | null; onClick?: () => void; note?: string }) {
  const content = <><span>{label}</span><strong>{displayNumber(count)}</strong>{note && <small>{note}</small>}</>;
  return onClick ? <button className="coverage-metric" onClick={onClick}>{content}</button> : <div className="coverage-metric">{content}</div>;
}
function CaseInspector({ title, records, close }: { title: string; records: CoverageCase[]; close: () => void }) {
  const [query,setQuery] = useState('');
  const [page,setPage] = useState(0);
  const selected = records.filter((record) => normalize(`${record.name} ${record.citation}`).includes(normalize(query)));
  const pages = Math.max(1,Math.ceil(selected.length / 25));
  const currentPage = Math.min(page,pages - 1);
  return <Section id="coverage-inspector" title={title} note={`${records.length.toLocaleString()} cases in this selection`}>
    <div className="coverage-actions"><label>Search these cases<input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} /></label><button onClick={close}>Close case inspection</button></div>
    <div className="coverage-table-wrap" tabIndex={0} role="region" aria-label="Selected cases"><table className="coverage-table"><thead><tr><th scope="col">Case</th><th scope="col">Court / jurisdiction</th><th scope="col">Decision</th><th scope="col">Verification</th><th scope="col">Content / status</th></tr></thead><tbody>{selected.slice(currentPage*25,(currentPage+1)*25).map((record) => <tr key={record.id || record.slug}><th scope="row">{record.contentStatus === 'Published' && record.slug ? <a href={`/cases/${encodeURIComponent(record.slug)}`}>{record.name} ↗</a> : record.name}<small>{record.citation || 'No citation recorded'}</small></th><td>{record.court}<small>{record.provinces.join(', ') || 'Unknown'}</small></td><td>{date(record.decisionDate)}</td><td>{record.verification}</td><td>{record.contentStatus}<small>{record.status}</small></td></tr>)}</tbody></table></div>
    {!selected.length && <p className="coverage-empty">No cases match this selection.</p>}
    {pages > 1 && <div className="coverage-actions"><button disabled={!currentPage} onClick={() => setPage(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {pages}</span><button disabled={currentPage === pages-1} onClick={() => setPage(currentPage+1)}>Next</button></div>}
  </Section>;
}

export function CoverageDashboard() {
  const [token,setToken] = useState('');
  const [snapshot,setSnapshot] = useState<CoverageSnapshot | null>(null);
  const [message,setMessage] = useState('');
  const [loading,setLoading] = useState(false);
  const [filters,setFilters] = useState<Filters>({...emptyFilters});
  const [inspection,setInspection] = useState<{ title: string; records: CoverageCase[] } | null>(null);
  const [communityGaps,setCommunityGaps] = useState(false);
  const [priorityView,setPriorityView] = useState('High Priority');
  const inspectorRef = useRef<HTMLDivElement>(null);
  async function load() {
    setLoading(true); setMessage(''); setSnapshot(null); setInspection(null);
    try {
      const response = await fetch('/api/admin/coverage',{ headers:{ Authorization:`Bearer ${token}` },cache:'no-store' });
      if (!response.ok) throw new Error(response.status === 401 ? 'The editor token was not accepted.' : 'Coverage could not be loaded. Try again.');
      const body = await response.json() as CoverageSnapshot;
      setSnapshot(body); setFilters({...emptyFilters});
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Coverage could not be loaded.'); }
    finally { setLoading(false); }
  }
  const cases = useMemo(() => filterCases(snapshot?.cases ?? [],filters),[snapshot,filters]);
  const inspect: Inspect = (title,records) => { setInspection({title,records}); requestAnimationFrame(() => { inspectorRef.current?.scrollIntoView({behavior:'smooth',block:'start'}); inspectorRef.current?.focus({preventScroll:true}); }); };
  const select = (key: keyof Filters,value: string) => { setFilters((current) => ({...current,[key]:value})); setInspection(null); };
  const reset = () => { setFilters({...emptyFilters}); setInspection(null); };
  const geography = rowsFor(cases,jurisdictions,(record) => record.provinces.length ? record.provinces : ['Unknown jurisdiction']);
  const courts = rowsFor(cases,[],(record) => [record.court]);
  const levels = rowsFor(cases,courtLevels,(record) => [record.level]);
  const groupRows = rowsFor(cases,groups,(record) => record.groups.length ? record.groups : ['Unknown group']);
  const topicRows = rowsFor(cases,snapshot?.topics.map((topic) => topic.name) ?? [],(record) => record.topics);
  const treatyRows = rowsFor(cases,snapshot?.treaties.map((treaty) => treaty.name) ?? [],(record) => record.treaties);
  const communityRows = rowsFor(cases,snapshot?.communities.map((community) => community.name) ?? [],(record) => record.communities);
  const endDecade = Math.floor(Number(snapshot?.generatedAt.slice(0,4) || new Date().getFullYear())/10)*10;
  const decades = rowsFor(cases,['Pre-1950',...Array.from({length:Math.max(0,(endDecade-1950)/10+1)},(_,index) => `${1950+index*10}s`)],(record) => [decade(record)]).sort((a,b) => a.name === 'Pre-1950' ? -1 : b.name === 'Pre-1950' ? 1 : a.name.localeCompare(b.name));
  const years = rowsFor(cases,[],(record) => [record.decisionDate.slice(0,4) || 'Unknown / no decision']).sort((a,b) => a.name.localeCompare(b.name));
  const gapRows = [{kind:'Jurisdiction',rows:geography.filter((row) => jurisdictions.includes(row.name))},{kind:'Decade',rows:decades.filter((row) => row.name !== 'Unknown / no decision')},{kind:'Court level',rows:levels.filter((row) => row.name !== 'Unclassified')},{kind:'Treaty',rows:treatyRows},{kind:'Indigenous group',rows:groupRows.filter((row) => groups.includes(row.name))},{kind:'Legal topic',rows:topicRows},{kind:'Community',rows:communityRows}].flatMap(({kind,rows}) => rows.map((row) => ({...row,kind})));
  const active = Object.values(filters).filter(Boolean).length;
  const p = snapshot?.pipeline;
  const available = (key: keyof NonNullable<typeof p>) => p ? p[key] : null;
  const options: {key:keyof Filters; label:string; values:string[]}[] = snapshot ? [
    {key:'province',label:'Province / territory',values:unique([...jurisdictions,...snapshot.cases.flatMap((c) => c.provinces)])},
    {key:'court',label:'Court',values:unique(snapshot.cases.map((c) => c.court))},
    {key:'level',label:'Court level',values:courtLevels},
    {key:'group',label:'Indigenous group',values:unique([...groups,...snapshot.cases.flatMap((c) => c.groups)])},
    {key:'treaty',label:'Treaty',values:unique([...snapshot.treaties.map((t) => t.name),...snapshot.cases.flatMap((c) => c.treaties)])},
    {key:'topic',label:'Legal topic',values:unique([...snapshot.topics.map((t) => t.name),...snapshot.cases.flatMap((c) => c.topics)])},
    {key:'verification',label:'Verification level',values:['Verified','Secondary Source','Needs Verification']},
    {key:'content',label:'Content status',values:['Draft','Published','Needs Verification']},
  ] : [];
  const treatyCommunityCount = (name: string) => {
    const treaty = snapshot?.treaties.find((item) => item.name === name);
    if (!treaty) return 'Not catalogued';
    const identities = new Set<string>();
    for (const community of snapshot?.communities ?? []) if (community.treaties.some((value) => [treaty.name,treaty.slug,treaty.id].map(normalize).includes(normalize(value)))) identities.add(normalize(community.name));
    for (const label of treaty.communities) { const community = snapshot?.communities.find((item) => [item.name,item.slug,item.id,...item.alternateNames].map(normalize).includes(normalize(label))); identities.add(normalize(community?.name ?? label)); }
    return identities.size;
  };
  return <>
    <section className="coverage-panel" aria-label="Editor access"><form className="coverage-auth" onSubmit={(event) => { event.preventDefault(); void load(); }}><label htmlFor="coverage-token">Editor token<input id="coverage-token" disabled={loading} type="password" autoComplete="off" value={token} onChange={(event) => { setToken(event.target.value); setSnapshot(null); setInspection(null); }} required /></label><button disabled={loading || !token}>{loading ? 'Loading…' : snapshot ? 'Refresh coverage' : 'Load coverage'}</button>{snapshot && <button type="button" onClick={() => { setToken(''); setSnapshot(null); setInspection(null); setMessage('Workspace locked.'); }}>Lock workspace</button>}</form><p className="coverage-note">Use the discovery review queue’s editor token. The token stays in memory for this tab.</p><p role="status">{message || (snapshot ? `Loaded ${snapshot.generatedAt.replace('T',' ').slice(0,19)} UTC · ${snapshot.storage === 'live' ? 'Curated collection + live records' : 'Curated collection only'}` : 'Coverage data is available only after authorization.')}</p></section>
    {snapshot && <>
      {snapshot.warnings.map((warning,index) => <p className="coverage-warning" role="status" key={index}>{warning}</p>)}
      <Section id="filters" title="Filter the collection" note="Filters apply to case coverage, priorities, quality checks and case activity. Discovery runs and catalogue totals remain global. Date bounds use decision dates; undated cases are excluded when a bound is set.">
        <div className="coverage-filters">{options.map((option) => <label key={option.key}>{option.label}<select value={filters[option.key]} onChange={(event) => select(option.key,event.target.value)}><option value="">All</option>{option.values.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>)}<label>Decision from<input type="date" value={filters.from} max={filters.to || undefined} onChange={(event) => select('from',event.target.value)} /></label><label>Decision through<input type="date" value={filters.to} min={filters.from || undefined} onChange={(event) => select('to',event.target.value)} /></label></div>
        <div className="coverage-actions"><p role="status"><b>{cases.length.toLocaleString()}</b> of {snapshot.cases.length.toLocaleString()} cases · {active} filters</p><button onClick={reset}>Reset filters</button></div>{filters.from && filters.to && filters.from > filters.to && <p className="coverage-warning">The start date must be on or before the end date.</p>}
      </Section>
      <nav className="coverage-jumps" aria-label="Dashboard sections">{[['overview','Overview'],['pipeline','Pipeline'],['geography','Geography'],['courts','Courts'],['time','Time'],['topics','Topics'],['treaties','Treaties'],['communities','Communities'],['groups','Groups'],['gaps','Priorities'],['quality','Data quality'],['activity','Activity']].map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>
      {!cases.length && <p className="coverage-warning">No cases match the current filters. Zero counts describe this selection; reset filters to assess the full collection.</p>}
      <div ref={inspectorRef} tabIndex={-1}>{inspection && <CaseInspector key={inspection.title} {...inspection} close={() => setInspection(null)} />}</div>
      <Section id="overview" title="Database overview" note="Click a case metric to inspect its records. Ongoing includes pending appeals. Verification and publication are separate dimensions.">
        <div className="coverage-kpis"><Metric label="Total cases" count={cases.length} onClick={() => inspect('All selected cases',cases)} />{['Published','Verified','Needs Verification','Draft','Secondary Source'].map((key) => <Metric key={key} label={key === 'Published' ? 'Published cases' : key} count={cases.filter((c) => c.quality.includes(key as QualityKey)).length} onClick={() => inspect(key,cases.filter((c) => c.quality.includes(key as QualityKey)))} />)}<Metric label="Ongoing cases" count={cases.filter((c) => c.ongoing).length} onClick={() => inspect('Ongoing cases',cases.filter((c) => c.ongoing))} /><Metric label="Appeal pending" count={cases.filter((c) => c.appeal).length} onClick={() => inspect('Appeal pending',cases.filter((c) => c.appeal))} /><Metric label="Indigenous communities" count={snapshot.communities.length} note="Global catalogue" /><Metric label="Treaties" count={snapshot.treaties.length} note="Global catalogue" /><Metric label="Legal topics" count={snapshot.topics.length} note="Global catalogue" /><Metric label="Courts represented" count={courts.filter((row) => row.name !== 'Unknown court').length} note="Current selection" /></div>
        <details className="coverage-details"><summary>Case statuses and counting rules</summary><p>Curated cases and stored CASE records are combined by slug or full citation, keeping the curated version where a seed overlaps. Discovery candidates are counted separately. A case can belong to multiple jurisdictions, groups, treaties, topics or communities; category percentages may exceed 100% in total. “Other” is an explicit recorded group; unknown groups are shown separately.</p><div className="coverage-statuses">{rowsFor(cases,[],(c) => [c.status]).map((row) => <button key={row.name} onClick={() => inspect(row.name,row.records)}>{row.name} <b>{row.count}</b></button>)}</div></details>
      </Section>
      <Section id="pipeline" title="Discovery pipeline" note="Global pipeline snapshot, unaffected by case filters. Search queries, newly queued URLs and processing attempts are cumulative from saved runs. Queue metrics describe current item states and can overlap.">
        <div className="coverage-kpis"><Metric label="Sources searched" count={available('queries')} note="Recorded search queries" /><Metric label="URLs discovered" count={available('urls')} note="Newly queued in saved runs" /><Metric label="Pages checked" count={available('processed')} note="Processing attempts, including retries" /><Metric label="Case candidates" count={available('candidates')} note="Queue items classified CASE" /><Metric label="Verified candidates" count={available('verified')} note="Primary / multiple verification" /><Metric label="Requiring review" count={available('review')} note="All record types" /><Metric label="Duplicates flagged" count={available('duplicates')} note="Stored duplicate links; not skip events" /><Metric label="Rejected" count={available('rejected')} note="Current queue state" /><Metric label="Failures" count={available('failures')} note="Current failed items; not search failures" /><Metric label="Seed records added" count={null} note="Not persisted in scan history" /></div>
        <p className="coverage-conversion"><strong>{p ? percent(p.verified,p.candidates) : '—'}</strong> verified case candidates / all case candidates{p ? ` · ${p.verified} / ${p.candidates}` : ''}</p><p className="coverage-note">Verified candidates can still require review or be rejected. A zero-candidate conversion rate is undefined. Sources searched counts queries, not distinct providers. Duplicate skips, seed additions and historical search failures are not persisted. <a className="coverage-inline-link" href="/admin">Open discovery review →</a></p>
        {!p ? <p className="coverage-empty">Discovery data unavailable.</p> : !snapshot.runs.length ? <p className="coverage-empty">No historical scan data available.</p> : <div className="coverage-table-wrap" tabIndex={0} role="region" aria-label="Recent discovery runs"><table className="coverage-table"><thead><tr>{['Date (UTC)','Mode','Status','Queries','URLs found','Pages checked','Candidates','Verified','Needs review','Duplicates','Rejected','Failures'].map((heading) => <th scope="col" key={heading}>{heading}</th>)}</tr></thead><tbody>{snapshot.runs.map((run) => <tr key={run.id}><th scope="row">{run.started_at.replace('T',' ').slice(0,16)}</th><td>{run.trigger_type}</td><td>{run.status}</td><td>{run.queries_run}</td><td>{run.urls_discovered}</td><td>{run.documents_processed}</td>{Array.from({length:6},(_,index) => <td key={index} title="Not recorded per run">—</td>)}</tr>)}</tbody></table></div>}<p className="coverage-note">Latest 20 saved runs. — means not recorded per run; it does not mean zero. In-progress runs may not yet have final counters.</p>
      </Section>
      <Section id="geography" title="Geographic coverage" note="All provinces and territories are shown. Canada / national and unknown records are kept separate. Multi-jurisdiction cases count once in each recorded jurisdiction."><CoverageTable rows={geography} inspect={inspect} /></Section>
      <Section id="courts" title="Court coverage" note={`${percent(cases.filter((c) => c.level === courtLevels[0]).length,cases.length)} of selected cases are Supreme Court of Canada records. Court levels are classified from recorded court names; unrecognized courts remain unclassified.`}><CoverageTable rows={levels} inspect={inspect} dates /><details className="coverage-details"><summary>Every represented court</summary><CoverageTable rows={courts} inspect={inspect} dates /></details></Section>
      <Section id="time" title="Coverage by time" note="Decision dates determine decades. Undated and active matters without a decision stay in the unknown / no decision row."><CoverageTable rows={decades} inspect={inspect} /><details className="coverage-details"><summary>Coverage by recorded year</summary><CoverageTable rows={years} inspect={inspect} /></details></Section>
      <Section id="topics" title="Legal topic coverage" note="Existing topic catalogue plus labels found in case records. Unmapped labels remain visible for editorial review."><CoverageTable rows={topicRows} inspect={inspect} /></Section>
      <Section id="treaties" title="Treaty coverage" note="Every catalogued treaty is included, even when it has no linked cases. Community counts describe the global catalogue, not the selected case subset."><CoverageTable rows={treatyRows} inspect={inspect} extra={{ headings:['Communities','Latest connected case','Treaty verification'],cells:(row) => { const latest = [...row.records].filter((c) => c.decisionDate).sort((a,b) => b.decisionDate.localeCompare(a.decisionDate))[0]; return [treatyCommunityCount(row.name),latest ? <button className="coverage-link" onClick={() => inspect(`Latest case · ${row.name}`,[latest])}>{latest.name}<small>{latest.decisionDate}</small></button> : 'No dated case',snapshot.treaties.find((t) => t.name === row.name)?.verificationLevel || 'Not catalogued']; } }} /></Section>
      <Section id="communities" title="Community coverage" note="Case links are combined from cases and catalogue relationships. Legal issue counts use distinct legal topics in the selected linked cases."><label className="coverage-checkbox"><input type="checkbox" checked={communityGaps} onChange={(event) => setCommunityGaps(event.target.checked)} />Coverage gaps only: catalogued communities with 0–2 cases</label><CoverageTable rows={communityRows.filter((row) => !communityGaps || row.count <= 2 && snapshot.communities.some((c) => c.name === row.name))} inspect={inspect} extra={{headings:['Province / territory','Group','Treaties','Legal issues'],cells:(row) => { const community = snapshot.communities.find((c) => c.name === row.name); return [community?.provinceTerritory || 'Not catalogued',community?.indigenousGroup || 'Not catalogued',community?.treaties.join(', ') || 'None recorded',unique(row.records.flatMap((c) => c.topics)).length]; }}} /></Section>
      <Section id="groups" title="Indigenous group coverage" note="Recorded group associations, including multi-group cases. Percentages are shares of selected cases, not shares of litigation in Canada."><CoverageTable rows={groupRows} inspect={inspect} /></Section>
      <Section id="gaps" title="Coverage gaps / priority backfills" note="Coverage priority reflects OpenCourt’s current dataset, not the actual volume of Indigenous litigation in that jurisdiction."><div className="coverage-actions"><label>Priority view<select value={priorityView} onChange={(event) => setPriorityView(event.target.value)}>{['High Priority','Medium Priority','Healthy','All'].map((value) => <option key={value}>{value}</option>)}</select></label><p>{active ? 'Priorities reflect the filtered selection.' : 'Priorities reflect the full available collection.'}</p></div><p className="coverage-note">High Priority = zero cases. Medium Priority = 1–2 cases or fewer than 20% of the largest category in the same dimension. Healthy = above these thresholds; it is not a claim of completeness. National, unknown and unclassified buckets are excluded from backfill ranking.</p><div className="coverage-table-wrap" tabIndex={0} role="region" aria-label="Backfill priorities"><table className="coverage-table"><thead><tr><th scope="col">Dimension</th><th scope="col">Category</th><th scope="col">Cases</th><th scope="col">Priority</th><th scope="col">Suggested focus</th></tr></thead><tbody>{gapRows.filter((row) => priorityView === 'All' || row.priority === priorityView).sort((a,b) => a.count-b.count || a.kind.localeCompare(b.kind)).map((row) => <tr key={`${row.kind}-${row.name}`}><td>{row.kind}</td><th scope="row"><button className="coverage-link" onClick={() => inspect(`${row.kind} · ${row.name}`,row.records)}>{row.name}</button></th><td>{row.count}</td><td><Priority value={row.priority} /></td><td>{row.priority === 'Healthy' ? 'Maintain source checks' : row.kind === 'Community' || row.kind === 'Treaty' ? 'Review existing associations, then search primary sources' : 'Target primary-source discovery and historical backfill'}</td></tr>)}</tbody></table></div>{!gapRows.some((row) => priorityView === 'All' || row.priority === priorityView) && <p className="coverage-empty">No categories at this priority.</p>}</Section>
      <Section id="quality" title="Data quality" note="Click any check to inspect its cases. Treaty association checks apply only to cases with treaty-related topics. Missing related cases means no stored connection; it does not prove a relationship should exist."><div className="coverage-kpis">{qualityKeys.map((key) => <Metric key={key} label={key} count={cases.filter((c) => c.quality.includes(key)).length} onClick={() => inspect(key,cases.filter((c) => c.quality.includes(key)))} />)}</div><p className="coverage-note">Placeholder detection flags known generic editorial phrases and TODO/TBD text. These are review prompts, not factual error determinations. Recency uses the recorded verification date and a 365-day threshold.</p></Section>
      <Section id="activity" title="Recent activity" note="Up to five cases per activity type, using recorded dates. These are current record timestamps, not an audit log. Discovery runs and recent relationships remain global."><div className="coverage-activity">{([{key:'createdAt',label:'Recently added'},{key:'lastVerified',label:'Recently verified'},{key:'updatedAt',label:'Recently updated'}] as const).map(({key,label}) => <div key={key}><h3>{label}</h3><ul>{cases.filter((c) => c[key] && (key !== 'lastVerified' || c.verification === 'Verified')).sort((a,b) => b[key].localeCompare(a[key])).slice(0,5).map((c) => <li key={c.id}><button className="coverage-link" onClick={() => inspect(label,[c])}>{c.name}</button><time>{c[key]}</time></li>)}</ul>{!cases.some((c) => c[key] && (key !== 'lastVerified' || c.verification === 'Verified')) && <p>No dated records.</p>}</div>)}</div><details className="coverage-details"><summary>Recently added relationships · global</summary>{snapshot.relationships.length ? <ul className="coverage-relationships">{snapshot.relationships.map((relation,index) => <li key={index}><b>{relation.title}</b> · {relation.relationship_type.replaceAll('_',' ')} → {relation.target_label}<small>{date(relation.created_at)}</small></li>)}</ul> : <p>{snapshot.storage === 'live' ? 'No recent relationship data available.' : 'Relationship data unavailable.'}</p>}</details><a className="coverage-inline-link" href="#pipeline">View recent discovery runs ↑</a></Section>
    </>}
  </>;
}
