import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PageShell, VerificationBadge } from "../../../components/SiteChrome";
import { communities, communityBySlug, topics } from "../../../data/catalog";
import { caseBySlug } from "../../../data/cases";

export function generateStaticParams() { return communities.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const item = communityBySlug((await params).slug); return { title: item ? `${item.name} | Community Profile` : "Community not found | OpenCourt", description: item ? `Court cases and legal issues connected to ${item.name}.` : undefined }; }
export default async function CommunityPage({ params }: { params: Promise<{ slug: string }> }) { const item = communityBySlug((await params).slug); if (!item) notFound(); const connected = item.caseSlugs.map(caseBySlug).filter(Boolean); return <PageShell><section className="page-hero community-detail-hero"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Communities", href: "/communities" }, { label: item.name }]} /><div className="detail-title-row"><div><p className="kicker">Community profile</p><h1>{item.name}</h1></div><VerificationBadge level={item.verificationLevel} /></div><dl className="profile-facts"><div><dt>Indigenous group</dt><dd>{item.indigenousGroup}</dd></div><div><dt>Province / territory</dt><dd>{item.provinceTerritory}</dd></div><div><dt>Treaty</dt><dd>{item.treaties.join(", ") || "No treaty connection recorded"}</dd></div><div><dt>Official website</dt><dd>{item.officialWebsite ? <a href={item.officialWebsite} target="_blank" rel="noreferrer">Visit official website ↗</a> : "Information not yet verified"}</dd></div></dl></section><section className="profile-content"><div className="profile-section"><div><p className="section-number">01</p><h2>Court cases</h2></div><div className="compact-case-list">{connected.map((entry) => entry && <Link href={`/cases/${entry.slug}`} key={entry.slug}><span>{entry.officialCitation}</span><div><h3>{entry.caseName}</h3><p>{entry.summaryShort}</p></div><b>→</b></Link>)}</div></div><div className="profile-section"><div><p className="section-number">02</p><h2>Legal issues</h2></div><div className="related-topic-row">{item.legalIssues.map((name) => { const topic = topics.find((entry) => entry.name === name); return topic ? <Link href={`/topics/${topic.slug}`} key={name}>{name} →</Link> : <span key={name}>{name}</span>; })}</div></div><div className="profile-section"><div><p className="section-number">03</p><h2>Active litigation</h2></div><p>No active litigation is currently published for this profile. This does not mean none exists; future entries require a verified court source and update date.</p></div><div className="profile-section"><div><p className="section-number">04</p><h2>Settlements &amp; claims</h2></div><p>Information not yet verified.</p></div><p className="last-verified">Last verified: <b>{item.lastVerified}</b></p></section></PageShell>; }
